### ISSUE TITLE
Add @types package

### ISSUE THREAD

**Issue by josecolella** [dividab/tsconfig-paths-webpack-plugin#16]
With the upgrade to new ts-node, the typescript compiler now enforces types for all dependencies. Is there a plan for an @types package. If you need help with this, please let me know.

**Comment by jonaskello** [comment]
I'm not sure I follow. Do you have a link to more info or an example of what this issue would solve?

**Comment by josecolella** [comment]
Basically upgrading to new ts-node, leads to transpilation error because ts-paths-webpack-plugin does not have a @types package. I'm asking if this is already in the roadmap. If it is not I can create a pull request with types.d.ts file

**Comment by jonaskello** [comment]
The plugin is actually written in typescript but it seems we do not currently include the types in the published npm package. So I guess we could do that, basically it is just about setting the types field in the package.json and including the .d.ts files in the publish.

**Comment by jonaskello** [comment]
One thing I don't really understand though is how you use a webpack plugin with ts-node? Do you execute webpack using ts-node?

**Comment by josecolella** [comment]
I don't understand it 100%, but I noticed that ts-node must be used under the hood, as upgrading to newest version leads to the warnings about types. As to your previous comment, that would be perfect. Also, I want to thank you for an amazing plugin.

**Comment by jonaskello** [comment]
Maybe this is related:

https://github.com/dividab/tsconfig-paths/issues/41

**Comment by jonaskello** [comment]
I could try to add the typings but I think more is going on so I would need to have some way of knowing if it fixes the issue. In this repo there is a small example that you can run with `yarn example`. This repo also uses ts-node and I upgraded it to 6.0.3. However I can still run `yarn example` without problems. I guess something in your setup is different? If you could create a small example repo that reproduced the problem it would be helpful in fixing it.

**Comment by josecolella** [comment]
I will create a small example with the console output.

**Comment by josecolella** [comment]
@jonaskello Here is a link to an asciicinema recording showing the update to latest ts-node (6.0.3). I show the steps in the installation, basically at the end you will see a message saying:
`Try `npm install @types/tsconfig-paths-webpack-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module 'tsconfig-paths-webpack-plugin';` (7016)`

**Comment by jonaskello** [comment]
I cannot find the link to the recording, did you forget to post it?

**Comment by jonaskello** [comment]
This seems to be the relevant error message:

```
❯ yarn watch                                                                            
yarn run v1.6.0                                                                         
$ NODE_ENV=development npx webpack --watch                                              
⨯ Unable to compile TypeScript                                                          
webpack.config.ts (1,32): Could not find a declaration file for module 'webpack-node-ext
ernals'. '/Users/jose.colella/Development/ci360-bff/node_modules/webpack-node-externals/
index.js' implicitly has an 'any' type.                                                 
  Try `npm install @types/webpack-node-externals` if it exists or add a new declaration 
(.d.ts) file containing `declare module 'webpack-node-externals';` (7016)               
webpack.config.ts (5,38): Could not find a declaration file for module 'tsconfig-paths-w
ebpack-plugin'. '/Users/jose.colella/Development/ci360-bff/node_modules/tsconfig-paths-w
ebpack-plugin/index.js' implicitly has an 'any' type.                                   
  Try `npm install @types/tsconfig-paths-webpack-plugin` if it exists or add a new decla
ration (.d.ts) file containing `declare module 'tsconfig-paths-webpack-plugin';` (7016) 
error Command failed with exit code 1.                                                  
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.    
```

It seems you are using typescript for your webpack config file. So your webpack config is probably run by ts-node?

**Comment by jonaskello** [comment]
Since you have a typescript file for webpack config, I guess you have something like ` import * as plugin from "tsconfig-paths-webpack-plugin"` at the top of that file? If so that would probably explain it.

**Comment by josecolella** [comment]
Correct. My webpack config is in Typescript. With the 6.* release ts-node is enforcing types files before transpilation.

I am importing the plugin with:
> import * as TsconfigPathsPlugin from 'tsconfig-paths-webpack-plugin';

**Comment by jonaskello** [comment]
I just published 3.1.0 which includes typescript typings. Could you try that?

**Comment by jonaskello** [comment]
Also updated the readme with a [typescript support](https://github.com/dividab/tsconfig-paths-webpack-plugin#typescript-support) section.

**Comment by josecolella** [comment]
Thanks for the update. Unfortunately still getting the issue:
`Try `npm install @types/tsconfig-paths-webpack-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module 'tsconfig-paths-webpack-plugin';` (7016)`

**Comment by jonaskello** [comment]
If you have not tried it already, you should modify your original import statement (the one with star import) to this:

```
import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin";
```

**Comment by josecolella** [comment]
Thanks. Changed the import to the above, though still getting the message:
```
Try npm install @types/tsconfig-paths-webpack-plugin if it exists or add a new declaration (.d.ts) file containing `declare module 'tsconfig-paths-webpack-plugin'; (7016)
```
Let me know if I can be of any help

**Comment by josecolella** [comment]
We are getting closer. The error that it outputs is:
```
tsconfig_paths_webpack_plugin_1.TsconfigPathsPlugin is not a constructor
```

**Comment by jonaskello** [comment]
That sounds like an error you would get if you use star import (`import * as TsconfigPathsPlugin`). Can you double check that you are using named import like this everwhere:

```ts
import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin";
```

**Comment by josecolella** [comment]
Yep tried both ways but no success

**Comment by jonaskello** [comment]
It will probably work if you do this:

```ts
import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin/lib/plugin";
```

Although that is not a very nice solution. The problem is to have a single index.js that both typescript can do `import` on, and regular JS with commonjs modules can do `require` on. I'm not sure how to accomplish that, if you have any ideas they are welcome :-).

**Comment by jonaskello** [comment]
Ok, so I published 3.1.3 where I finally think we have an index.js that supports all these ways of importing:

```
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
import TsconfigPathsPlugin from "tsconfig-paths-webpack-plugin";
import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin";
```

Give it a try and see if it works.

**Comment by josecolella** [comment]
No more issues showing. @jonaskello Thank you so much for your help with this issue. Amazing plugin.

**Comment by josecolella** [comment]
You can close this issue.
